name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: pip install uv
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run black (code formatting check)
      run: uv run black --check src/
    
    - name: Run flake8 (linting)
      run: uv run flake8 src/
    
    - name: Run mypy (type checking)
      run: uv run mypy src/
    
    - name: Run tests
      run: uv run pytest tests/ -v